name: Health Report

on:
  schedule:
    - cron: "10 01 * * *"
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout codes"
        uses: actions/checkout@v2

      - name: "Set python"
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade requests
          python -m pip install --upgrade pytz

      - name: "GoodHealth"
        env:
          GHUSERNAME: ${{ secrets.USERNAME }}
          GHPASSWORD: ${{ secrets.PASSWORD }}
          GHCITY: ${{ secrets.CITY }}
          GHFORCE: ${{ secrets.FORCE }}
          GHVPN: ${{ secrets.VPN }}
          GHSENDKEY: ${{ secrets.SENDKEY }}
        run: python GoodHealth.py
